spring:
  application:
    name: loyalty-kata

  datasource:
    url: jdbc:h2:mem:loyaltydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

loyalty:
  points:
    expiration-years: 1
    notification-days-before-expiration: 7